In [1]:
import numpy as np

In [2]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [3]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [4]:
np.eye(3, k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.eye(3, k=3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])